config/routes.rb
Rails.application.routes.draw do
  get '/ask', to: "coaching#ask"
  get '/answer', to: "coaching#answer"



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/coaching_controller.rb
class CoachingController < ApplicationController
  def ask
  end

  def answer
    @query = params[:query]
    @answer = nil
    if @query == "hello"
        @answer = "Hey, ya!"
      elsif your_message.end_with? "?"
        @answer = "Sorry, I have no idea!"
      else
        @answer = "Oh, I'm not so sure."
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/coaching_helper.rb
module CoachingHelper
end

app/views/coaching/answer.html.erb
<div class="container">
  <h3>Your query is:</h3>
  <%= @query %>

  <h3>The answer is:</h3>
  <%= @answer %>

  <hr>
  <%= link_to("Ask a new question", ask_path) %>

</div>

app/views/coaching/ask.html.erb
<div class="container">
  <h1>Speak to your coach</h1>

  <form action="/answer" method="get">
    <label for="question">Speak to your coach</label>
    <input type="text" id="question" name="query" placeholder="what time is it?">
    <input type="submit" value="Go on!">
  </form>

  <hr>
  <%= link_to("Go to the list of answers", answer_path) %>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsStupidCoaching</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>